#ifndef CPU_FEATURES_H
#define CPU_FEATURES_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef uint64_t AndroidCpuFamily;
typedef uint64_t AndroidCpuFeatures;

#define ANDROID_CPU_FAMILY_ARM 1
#define ANDROID_CPU_ARM_FEATURE_ARMv7 1
#define ANDROID_CPU_ARM_FEATURE_VFPv3 2
#define ANDROID_CPU_ARM_FEATURE_NEON 4
#define ANDROID_CPU_ARM_FEATURE_LDREX_STREX 8
#define ANDROID_CPU_ARM_FEATURE_VFPv2 16
#define ANDROID_CPU_ARM_FEATURE_VFP_D32 32
#define ANDROID_CPU_ARM_FEATURE_VFP_FP16 64
#define ANDROID_CPU_ARM_FEATURE_VFP_FMA 128
#define ANDROID_CPU_ARM_FEATURE_NEON_FMA 256
#define ANDROID_CPU_ARM_FEATURE_IDIV_ARM 512
#define ANDROID_CPU_ARM_FEATURE_IDIV_THUMB2 1024
#define ANDROID_CPU_ARM_FEATURE_iWMMXt 2048
#define ANDROID_CPU_ARM_FEATURE_AES 4096
#define ANDROID_CPU_ARM_FEATURE_PMULL 8192
#define ANDROID_CPU_ARM_FEATURE_SHA1 16384
#define ANDROID_CPU_ARM_FEATURE_SHA2 32768
#define ANDROID_CPU_ARM_FEATURE_CRC32 65536

// ARM64 features
#define ANDROID_CPU_ARM64_FEATURE_FP 1
#define ANDROID_CPU_ARM64_FEATURE_ASIMD 2
#define ANDROID_CPU_ARM64_FEATURE_AES 4
#define ANDROID_CPU_ARM64_FEATURE_PMULL 8
#define ANDROID_CPU_ARM64_FEATURE_SHA1 16
#define ANDROID_CPU_ARM64_FEATURE_SHA2 32
#define ANDROID_CPU_ARM64_FEATURE_CRC32 64

uint64_t android_getCpuFeatures(void);

#ifdef __cplusplus
}
#endif

#endif
